### ISSUE TITLE
.env.example more common than .env.sample

### ISSUE THREAD

**Issue by devinus** [rolodato/dotenv-safe#1]
`.env.example` seems to be a much more common filename than `.env.sample` in both Ruby and Node land. Perhaps consider using it as the default?

EDIT: Also this module is genius.

**Comment by rolodato** [comment]
Thanks! I just merged #2 for this.

**Comment by rolodato** [comment]
@devinus @motdotla 2.0.0 has been released.

**Comment by devinus** [comment]
Amazing!
