### ISSUE TITLE
dotenv-safe/config does not support configuration options by environment variable; dotenv/config does

### ISSUE THREAD

**Issue by ccw-morris** [rolodato/dotenv-safe#126]
In the description for `dotenv/config`, it includes the ability to set `dotenv` configuration options via env var: https://www.npmjs.com/package/dotenv
> `DOTENV_CONFIG_<OPTION>=value node -r dotenv/config your_script.js`

However, this issue - https://github.com/motdotla/dotenv/issues/423 - explains that only works when
> using `dotenv/config` (usually via preloading)

However, the code for dotenv-safe makes a requires call to `dotenv` not `dotenv/config`: https://github.com/rolodato/dotenv-safe/blob/master/index.js#L3
And the code for `dotenv-safe/config` (https://github.com/rolodato/dotenv-safe/blob/master/config.js) replicates the CLI config (https://github.com/motdotla/dotenv/blob/master/lib/cli-options.js), but not the newer ENV options (https://github.com/motdotla/dotenv/blob/master/lib/env-options.js).

This means that the environment variables (e.g. `DOTENV_CONFIG_PATH`) are not recognised when using `dotenv-safe/config`. And unfortunately I cannot use the CLI configuration options because I'm running webpack, which fails if it there is a CLI option that it doesn't recognise.

These are the scripts that I've tried:
`DOTENV_CONFIG_PATH=../../.env node -r dotenv/config $(yarn bin webpack)` - this loads the correct .env file, doesn't perform the safety check, and then runs webpack with the variables from the .env file.
`DOTENV_CONFIG_PATH=../../.env node -r dotenv-safe/config $(yarn bin webpack)` - this does not load the correct .env file and then fails on the safety check due to missing env vars.

For now, I can require `dotenv-safe` in the entry point to my application instead of using `dotenv-safe/config`. But, it would be nice to be able to use the newer functionality.

**Comment by rolodato** [comment]
Hi @ccw-morris, apologies for the late reply here. We're planning to move `dotenv` to a peer dependency of `dotenv-safe` (see https://github.com/rolodato/dotenv-safe/issues/128), which would make it unnecessary to copy this behavior from `dotenv` into `dotenv-safe`. This means that your application will choose which `dotenv` version gets used.

As such, the best path forward would probably be to require both `dotenv/config` and `dotenv-safe/config`. For example:

```
DOTENV_CONFIG_PATH=../../.env node -r dotenv/config -r dotenv-safe/config $(yarn bin webpack)
```

This will cause `dotenv/config` to run first, which loads `.env` into the environment, and afterwards `dotenv-safe/config` runs, which validates that environment against your `.env.example` file.

This approach should work with the current version of `dotenv-safe`, so you don't need to wait until a new release. Let me know if that works for you.

**Comment by rolodato** [comment]
`dotenv-safe` 9.0.0 is now published to npm and has `dotenv` as a peer dependency, which means you can now choose which `dotenv` version your application uses. I'll close this but happy to continue the discussion if needed!

**Comment by jraoult** [comment]
@rolodato I think there is still an issue with `DOTENV_CONFIG_EXAMPLE`. You might not want to support it but I thought I mention it just in case. You can find a reproduction here: https://stackblitz.com/edit/stackblitz-starters-6hzn9k?file=package.json&view=editor but the gist of it is:

I'm using [tsx](https://github.com/privatenumber/tsx)'s loader to run my code in Node 20 with a custom `.env` file path:

```bash
DOTENV_CONFIG_PATH=src/.deploy.env DOTENV_CONFIG_EXAMPLE=src/.deploy.env.example node --import tsx/esm --require dotenv-safe/config src/myApp.ts
```

but it fails with:

```bash
Error: ENOENT: no such file or directory, open '.env.example'
```

After investigation I discover `dotenv-safe` runs twice when preloaded (aka `--require`) in conjunction when using `tsx/esm` loader (aka `--import`). I suspect it runs once in the actual program and once in the loader but in the later the arguments are not passed. In my app case, it means the `dotenv_config_*` arguments are not present in the loader and `dotenv-safe` throws an error.  I wrote a patch for this that I apply thanks to yarn's patch's protocol:

```patch
diff --git a/config.js b/config.js
index 849330e48eb1ee3e720a9ef415f55817b845ea95..d055a38d0aa465265b232908437b745898174ddb 100644
--- a/config.js
+++ b/config.js
@@ -1,5 +1,13 @@
 (function () {
-    var options = {};
+    var options = Object.fromEntries(
+        Object.entries(process.env)
+            .filter(([key]) => key.startsWith("DOTENV_CONFIG_"))
+            .map(([key, value]) => [
+              key.replace("DOTENV_CONFIG_", "").toLowerCase(),
+              value,
+            ]),
+    );
+
     process.argv.forEach(function (val) {
         var matches = val.match(/^dotenv_config_(.+)=(.+)/);
         if (matches) {
```

**Comment by jraoult** [comment]
There you go @rolodato : https://github.com/rolodato/dotenv-safe/pull/134.
