### ISSUE TITLE
Upgrade `dotenv` version?

### ISSUE THREAD

**Issue by karlhorky** [rolodato/dotenv-safe#128]
Hi there! Thanks for `dotenv-safe`!

Would it be possible to upgrade the `dotenv` dependency? It is currently set at `^8.2.0`, but the latest version is `16.0.0`.

An alternative to upgrading `dotenv` would be to move `dotenv` to `peerDependencies` and accept any version above `8.2.0`, which would allow consuming projects to choose their version.

**Comment by vincentvella** [comment]
I forked this repo, set dotenv to a peer dependency, and published to npm under `dotenv-safer`, doesn't appear this repo is actively maintained, appreciated the legwork though so I'll keep my fork active and attributions + licensing still point back here
https://github.com/vincentvella/dotenv-safer

**Comment by karlhorky** [comment]
I've asked if @motdotla would be open to absorbing the functionality of `dotenv-safe` into `dotenv` as a separate, opt-in import path:

- https://github.com/motdotla/dotenv/issues/709

**Comment by karlhorky** [comment]
### Workaround

If you want to use simple functionality similar to `dotenv-safe` (mostly taken from [here](https://github.com/rolodato/dotenv-safe/blob/1ab395c2045bc8a2737da1a683cb6d56605a08f4/index.js#L21-L48)), then here's a super simple version, without any configurability / options:

```ts
import fs from 'node:fs';
import dotenv from 'dotenv';

dotenv.config();

// Replacement for unmaintained dotenv-safe package
//
// Alternative to dotenv absorbing the functionality of dotenv-safe:
// https://github.com/motdotla/dotenv/issues/709
const unconfiguredEnvVars = Object.keys(
  dotenv.parse(fs.readFileSync('.env.example')),
).filter((exampleKey) => !process.env[exampleKey]);

if (unconfiguredEnvVars.length > 0) {
  throw new Error(
    `.env.example environment variable${
      unconfiguredEnvVars.length > 1 ? 's' : ''
    } ${unconfiguredEnvVars.join(', ')} not configured in .env file`,
  );
}
// End replacement for dotenv-safe
```

Prints messages like this:

```bash
Error: .env.example environment variables A, ABB not configured in .env file
    at <anonymous> (/Users/k/p/project/config.ts:15:9)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by bellcory99** [comment]
Get

**Comment by rolodato** [comment]
Hi all, sorry for the radio silence. I'm planning on releasing a new version that has `dotenv` as a peer dependency. That way we can avoid the busywork of trying to keep up with the `dotenv` version and allow users to have whatever version they want.

Also, @motdotla has offered to assist with maintenance for this project, so I'd like to get his approval on this approach first (see https://github.com/motdotla/dotenv/pull/714#issuecomment-1928550190).

**Comment by motdotla** [comment]
@rolodato i think peerDependency is a great move. other libs do the same to good effect.

(if you run into `dotenv` not exposing data or a method that you need, just let me know.)

**Comment by rolodato** [comment]
`dotenv-safe` 9.0.0 is now published to npm and has `dotenv` as a peer dependency. Closing, thanks all for the input!
