### ISSUE TITLE
Don't overwrite environment variables that were already set

### ISSUE THREAD

**Issue by rolodato** [rolodato/dotenv-safe#17]
This is breaking the behavior described here: https://github.com/motdotla/dotenv/tree/fdd0923e82e12a6e29b65898990201857141e75d#what-happens-to-environment-variables-that-were-already-set

> We will never modify any environment variables that have already been set. In particular, if there is a variable in your .env file which collides with one that already exists in your environment, then that variable will be skipped. This behavior allows you to override all .env configurations with a machine-specific environment, although it is not recommended.

**Comment by bfelbo** [comment]
This is not obvious behavior as a developer. Would it be possible to have an option for overwriting or at least print warnings when your local `.env` file has variables that are already defined in env?
