### ISSUE TITLE
Missed file MissingEnvVarsError.js in 4.0.0 version during install

### ISSUE THREAD

**Issue by galk-in** [rolodato/dotenv-safe#19]
There is the error on new version. MissingEnvVarsError.js is missed in package.json file list, so we didn't publish the file.

**Comment by rolodato** [comment]
Amateurish mistake on my end, sorry about that. I'll review the PR later today and make a new release.

**Comment by rolodato** [comment]
Released a fix in 4.0.1. Thanks for reporting!
