### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by galkin** [rolodato/dotenv-safe#22]
Hi, @rolodato. You are making an amazing package. Let's make it better with Continues Integration. 

- [x] Add [travis](https://travis-ci.org) integration
- [x] Add travis.yaml file for the configuration 
- [ ] Add autopublising to npm on new release
- [ ] Add [coveralls.io](https://coveralls.io) integration
- [ ] Add code coverage report
- [x] Add badges to the Readme

This issue can not to been resolved with pull requests only. But I can help as consultant for any questions.

**Comment by rolodato** [comment]
Thanks for the kind words! You read my mind, this was next on my list - hopefully I'll be able to get it done this week.

**Comment by rolodato** [comment]
Hi @galkin, for now I don't think I'll add code coverage or autopublishing integrations - I've already integrated CI with Travis and added a build status badge to the README, so closing this issue. Thanks again!
