### ISSUE TITLE
Missing variable names not present in new error message (Node 7 only)

### ISSUE THREAD

**Issue by mmwtsn** [rolodato/dotenv-safe#23]
As of v4 if a variable is present in `.env.example` and missing from `.env` the name is not returned.

Test steps to recreate (output truncated slightly for clarity):

```bash
# Setup example project
$ mkdir dotenv-safe-test && cd $_
$ npm init -y
$ echo $'EXAMPLE_TEST_VAR_1=\nEXAMPLE_TEST_VAR_2=' > .env.example
$ echo $'EXAMPLE_TEST_VAR_1=true' > .env
$ echo $'"use-strict";\nrequire("dotenv-safe").load();\nconsole.log("Testing.");' > index.js

# NOTE - no variable names.
$ npm install dotenv-safe@4.0.1
$ node index.js
Error
    at Object.config (/Users/mwatson/Desktop/dotenv-safe-test/node_modules/dotenv-safe/index.js:37:19)

# NOTE - variable names.
$ npm install dotenv-safe@3.0.0
$ node index.js
Error: Missing environment variables: EXAMPLE_TEST_VAR_2
```

**Comment by rolodato** [comment]
Hi! Tried the same steps, can't reproduce on macOS 10.12.2 / Node 6.9.2. This is the output I'm getting:

```
$ node index.js

/Users/rolodato/git/dotenv-safe-test/node_modules/dotenv-safe/index.js:37
            throw new MissingEnvVarsError(allowEmptyValues, options.path || '.env', sample, missing, dotenvResult.error);
            ^
MissingEnvVarsError: The folowing variables are defined in .env.example but are not defined in the environment: EXAMPLE_TEST_VAR_2.
Make sure to add them to .env or directly to the environment.
If you expect any of these missing variables to be empty, you can use the allowEmptyValues option:

require('dotenv-safe').load({
  allowEmptyValues: true
});
```

Which version of Node and OS are you using?

**Comment by rolodato** [comment]
Just tried all latest versions of Node from 0 to 6, same (correct) behavior on all of them.

**Comment by mmwtsn** [comment]
Interesting.

I'm running Node.js v7.0.0.

**Comment by mmwtsn** [comment]
Ah, there it is.

I tested this against Node v7.0.0 when I wrote this. I'm seeing the same output from v7.3.0 (current).

**Comment by rolodato** [comment]
Yes, seems like something changed on Node 7 that's causing this. Thanks for pointing it out, will do some digging.

**Comment by mmwtsn** [comment]
Great, thanks!

I tried poking around for a few minutes but I'm not sure where this is coming from.

**Comment by rolodato** [comment]
Seems that removing this line from the `MissingEnvVarsError` definition fixes it:

```js
Error.captureStackTrace(this, this.constructor);
```

```
$ node --version
v7.3.0
$ node index.js
Testing.

/Users/rolodato/git/dotenv-safe-test/node_modules/dotenv-safe/index.js:39
            throw error;
            ^
MissingEnvVarsError: The folowing variables are defined in .env.example but are not defined in the environment: EXAMPLE_TEST_VAR_2.
Make sure to add them to .env or directly to the environment.
If you expect any of these missing variables to be empty, you can use the allowEmptyValues option:

require('dotenv-safe').load({
  allowEmptyValues: true
});
```

The Node 6 and 7 docs for `captureStackTrace` are identical, so this seems to be either a regression or an undocumented breaking change:

* https://nodejs.org/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt
* https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt

**Comment by rolodato** [comment]
Actually it seems this was a bugfix, since the description is correct:

> Creates a `.stack` property on `targetObject`, which when accessed returns a string representing the location in the code at which `Error.captureStackTrace()` was called.

`captureStackTrace` is meant to hide superfluous information from stack traces, and that's what we're accidentally doing here. Will fix this ASAP.

**Comment by rolodato** [comment]
Fixed and published in 4.0.2. Thanks again!

**Comment by rolodato** [comment]
@mmwtsn Just to make sure, could you confirm if 4.0.2 works for you as expected?

**Comment by mmwtsn** [comment]
Looks good!

Thanks for turning around the patch so quickly. That was an interesting one.
