### ISSUE TITLE
Preload with --require flag?

### ISSUE THREAD

**Issue by joshuajabbour** [rolodato/dotenv-safe#3]
This doesn't appear to work with the `--require` flag, [as dotenv does](https://github.com/motdotla/dotenv#preload). I'm still in the process of debugging to figure out why and see if I can provide a fix, but I figured I'd open a ticket now.

**Comment by rolodato** [comment]
Thanks for contributing @joshuajabbour !

**Comment by rolodato** [comment]
2.2.0 has been released.
