### ISSUE TITLE
Provide ability to encrypt the file for better security

### ISSUE THREAD

**Issue by stormit-vn** [rolodato/dotenv-safe#31]
We're currently not using this util because it doesn't support to encrypt the environment file as it contains sensitive information. Some our clients want to hide the information as much as possible for normal user. For now, we are using a helper class to load environment variables supports encrypt/decrypt the file based on the secret key (i.e. a .dat file stored somewhere that the app should know and read it contents) - using cryptoJS.AES.encrypt(input, key),  cryptoJS.AES.decrypt(encryptedStr,  key)

Hence, I would like to raise this issue to know other approaches and looking for this util can be updated and support that kind of feature.

**Comment by piranna** [comment]
Would the encryption be in a per field basis, or the full file at all? Where would you store the decription key and how?

**Comment by stormit-vn** [comment]
@piranna  I would say it will be file encryption since all fields are sensitive information. In relation to the key, as mentioned above, where can provide a configuration property to allow user specify a key or a secret file (i.e. a .dat file).

**Comment by Zertz** [comment]
You can always use [git-crypt](https://github.com/AGWA/git-crypt) to encrypt `.env` within the repo but typically environment variables shouldn't be commited.

**Comment by rolodato** [comment]
Sorry, I think this is out of scope for this library. If plain dotenv supported something like this I might consider it.
