### ISSUE TITLE
Do the checkin also for `parse` function

### ISSUE THREAD

**Issue by piranna** [rolodato/dotenv-safe#32]
https://github.com/rolodato/dotenv-safe/blob/78f290eca78c700b580082b079c63f9866004192/index.js#L46

`parse()` function is used directly from `dotenv`, without doing the checking for the entries in the `.env.example` file. Add the checkings so it could be used in arbitrary objects instead of only `process.env`.

**Comment by rolodato** [comment]
Hi @piranna, could you describe your use case for this? I've never used `parse` directly, just included it in case others depend on it.
