### ISSUE TITLE
Add option allowUnusedValues and UnusedEnvVarsError

### ISSUE THREAD

**Issue by romaleev** [rolodato/dotenv-safe#37]
Add option `allowUnusedValues` and `UnusedEnvVarsError`
```
If a variable is not defined in the example file, but present in the environment, disabling this option will throw an error after loading. Defaults to true.
```

**Comment by henrikbernstrom** [comment]
We are stuck with a situation in my current project which would probably benefit from a solution like the one mentioned above. Could you please verify that the definitions below are invalid, in the time of writing, with dotenv in conjunction with dotenv-safe? (A_MARKET_SPECIFIC_ID would be `undefined`?)

```
.env
AN_ORDINARY_PROPERTY=123abc
A_MARKET_SPECIFIC_ID=jdDJDJKEdkl3902djl
```

````
.env.example
AN_ORDINARY_PROPERTY=
```

**Comment by shmaram** [comment]
This is a very good feature, we really need this one . can you tell if there is a plan to develop it?

**Comment by rolodato** [comment]
I don't understand how this would work exactly - there will always be some environment variables defined by the system such as `USER`, `LANG` or `PWD`, so even if you don't include these variables in `.env` specifically there will always be some "unused" environment variable somewhere.

`.env` is meant to be a dumb file that gets merged with the current environment, and it shouldn't matter where the variables came from as long as they're present in the environment at runtime. Adding an option like this means that `.env` becomes special - in the example that @henrikbernstrom provided, would it be an error if `A_MARKET_SPECIFIC_ID` was provided in the environment externally? I don't think this use case is common enough (or difficult enough to work around) to merit the increased cognitive overhead of using this library.

If you really need to do this, you can look at the `parsed` and `required` objects returned by `config()` and use them to make the checks that you need. I'll close this as I'm not convinced it's a worthwhile feature, but happy to continue discussing if anyone feels particularly strongly about it.
