### ISSUE TITLE
Typescript string | undefined 

### ISSUE THREAD

**Issue by ravilution** [rolodato/dotenv-safe#39]
While I am using Typescript `process.env` value type is `string | undefined`. It forces me to write additional code to check if my value from process.env is undefined or not, before using it. If I am using dotenv-safe, I should be able to avoid writing those extra code. Am I correct? But, I am unable to. Because of type issues. Can we solve it?

**globals.d.ts**
```javascript
interface ProcessEnv {
        [key: string]: string | undefined;
    }
```

**Comment by rolodato** [comment]
I don't think there's a good way to solve this. The environment variables that dotenv-safe guarantees to exist are defined at run time (loaded once from the example file), so there's no way to statically enforce these checks. If you tried to access any other environment variable, you would still need to check that it's defined.

I'm not sure what a good alternative is here as I've not needed to solve this problem for TypeScript before, but I don't think there's anything that we can do here to improve this.

**Comment by rigwild** [comment]
Here is a solution I use to fix the problem.
```ts
import path from 'path'
import dotenvSafe from 'dotenv-safe'

// Load environment configuration
dotenvSafe.config({
  path: path.resolve(__dirname, '..', '.env'),
  example: path.resolve(__dirname, '..', '.env.example')
})

export const {
  ARG1,
  ARG2
} = <{ [key: string]: string }>process.env
```

**Comment by Maxim-Mazurok** [comment]
Yeah, I don't see good way to provide types either, even if dotenv would return an object with env vars - it has no way of knowing types defined in your example.

I guess the best way to solve this is by defining requiredEnvVars in TS and then having a unit test to verify that all requiredEnvVars are present in `.env.example`.

Here's my version:
```ts
import * as dotenv from "dotenv-safe";

dotenv.config(); // will load .env if it exists, and will validate all variables from example are defined in process.env

const requiredEnvVariables = [
  // TODO: add a test to check if all required env variables are defined in .env.example
  "PORT",
  "ANDROID_APP_WEB_CLIENT_ID",
  "ANDROID_APP_WEB_CLIENT_SECRET",
  "SERVER_PUBLIC_URL",
] as const;

const env: Record<(typeof requiredEnvVariables)[number], string> = {
  PORT: "",
  ANDROID_APP_WEB_CLIENT_ID: "",
  ANDROID_APP_WEB_CLIENT_SECRET: "",
  SERVER_PUBLIC_URL: "",
};

requiredEnvVariables.forEach((key) => {
  if (!process.env[key]) {
    console.error(`Missing ${key} env variable`);
    process.exit(1);
  }
  env[key] = process.env[key];
});

export { env };
```
