### ISSUE TITLE
Export to environment?

### ISSUE THREAD

**Issue by ericclemmons** [rolodato/dotenv-safe#40]
With environment variables defined via `.env`, it'd be useful to support the following:

- `node -r 'dotenv-safe/register' somescript.js`

  This way the environment is set without customizing `somescript.js` to include `require('dotenv-safe').load()`

**Comment by rolodato** [comment]
You can do this actually! Try `node -r dotenv-safe/config somescript.js`. I've added some documentation in the README about this: https://github.com/rolodato/dotenv-safe/commit/c64d36b90c4eaec7a6111e287336486acca50ebe
