### ISSUE TITLE
Defaults?

### ISSUE THREAD

**Issue by frontsideair** [rolodato/dotenv-safe#43]
I really like this package as it won't allow your program to run without environment variables. But sometimes there are sane defaults that don't require being overridden, like the port number for the database. For those cases, this library can optionally read a `.env.default` file and fill values from that if they aren't defined otherwise.

I see that #30 was closed with a very good reason, but in this case you'd never put a default value for things like usernames and passwords. Only for sane defaults.

**Comment by frontsideair** [comment]
On second thought, I mistook `dotenv-extended` for `dotenv-expand`, which doesn't look like it support everything I need. But `dotenv-extended` is golden.

**Comment by frontsideair** [comment]
I'm reopening this as `dotenv-extended` doesn't act like this package, and the option to throw on missing vars doesn't work when preloaded.

**Comment by anishkny** [comment]
> I'm reopening this as `dotenv-extended` doesn't act like this package, and the option to throw on missing vars doesn't work when preloaded.

@frontsideair can you elaborate on this ☝️

If you use `.env.schema` and `errorOnMissing: true`, then `dotenv-extended` **does** error on missing env vars. E.g. see below:

```bash
$ cat .env.schema
FOO=

$ cat index.js
require('dotenv-extended').load({
  errorOnMissing: true,
  includeProcessEnv: true,
});

$ node index.js
~/workspace/dotenv-extended-test/node_modules/dotenv-extended/lib/index.js:59
      throw new Error('MISSING CONFIG VALUES: ' + missingKeys.join(', '));
      ^

Error: MISSING CONFIG VALUES: FOO      # <------ GOOD! It should error on missing FOO.
    at Object.config (~/workspace/dotenv-extended-test/node_modules/dotenv-extended/lib/index.js:59:13)
    at Object.<anonymous> (~/workspace/dotenv-extended-test/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Am I missing something?

**Comment by frontsideair** [comment]
@anishkny A bit late, but reading my original comment, it seems like `errorOnMissing` wasn't working when used with `node -r dotenv-extended/config`. It may be added after my comment but now it seems like you can pass options prefixed with `dotenv_config_`, [as documented](https://www.npmjs.com/package/dotenv-extended#load-configs-from-command-line).

I guess I can close this now.
