### ISSUE TITLE
There should be a option allow particular variable to not to be present in .env Like "port" is present in .env.example and not in .env

### ISSUE THREAD

**Issue by skt1598** [rolodato/dotenv-safe#45]

**Comment by dotnetCarpenter** [comment]
@skt1598 looks like what you want is what PR https://github.com/rolodato/dotenv-safe/pull/41 is solving.

**Comment by imjordanxd** [comment]
I would also like this feature

**Comment by rolodato** [comment]
We've decided to not implement this - see https://github.com/rolodato/dotenv-safe/pull/98#issuecomment-1930166724 for an explanation. I'll close this issue but happy to continue the discussion!
