### ISSUE TITLE
Option allowEmptyValues set to true is not working

### ISSUE THREAD

**Issue by Yosr-Ch** [rolodato/dotenv-safe#58]
node version: v10.20.1
dotenv-safe version: 8.2.0
I set the `allowEmptyValues` to true but I'm still getting the MissingEnvVarsError.
Here is my code:
```
require('dotenv-safe').config({
  allowEmptyValues: true,
  path: path.join(__dirname, '../../.env'),
  example: path.join(__dirname, '../../.env.example'),
});
```
I couldn't figure out what I'm missing here. Thank you for your help!

**Comment by antonedvard** [comment]
same issue here, the `allowEmptyValues` set to `true` does nothing.

**Comment by jehincastic** [comment]
@Yosr-Ch @antonedvard 

If you have an .env.example file and .env file as mentioned below it will even throw an error with the **allowEmptyValues** as **true** if that is your case this will help.

```dosini
# .env.example, committed to repo
SECRET=
TOKEN=
KEY=
```

```dosini
# .env, private
SECRET=topsecret
TOKEN=
```
The **allowEmptyValues** just allows to have an empty value in the .env file but does not allow to skip a key in the .env file.

So the .env file should look like this to work with **allowEmptyValues: true**

```dosini
# .env, private
SECRET=topsecret
TOKEN=
KEY=
```

**Comment by rolodato** [comment]
(almost 4 years later... 💀)

@jehincastic's description is correct. Note that the option is named allowEmpty**Values**, meaning that it only cares about the values and not the presence of keys.
