### ISSUE TITLE
validate missing variables in .env

### ISSUE THREAD

**Issue by shmaram** [rolodato/dotenv-safe#69]
Hi 

Is there an option to validate that all the variables in .env are also in .env.example ? 
example : 

**.env** 
A=1
B=2
C=

**.env.example:**
A=
B=

this should throw an error

**Comment by rolodato** [comment]
Hi, sorry for the late reply! There is not an option for this, and I don't think it will be added. I'll close this issue but happy to continue the discussion if there's a good use case for it.
